services:
  frontend:
    image: team2/literature/frontend:production
    container_name: literature-frontend1
    ports:
      - "3001:3000"
    restart: always
    stdin_open: true

  frontend-backup:
    image: team2/literature/frontend:production
    container_name: literature-frontend2
    ports:
      - "3002:3000"
    restart: always
    stdin_open: true
